/**
 * LogicalView/simulation/elevator/elevator_UI/imp_elevator_UI/ButtonCall.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::imp_elevator_UI::ButtonCall uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:31 (24 novembre 2014) $
 */
package simulation.elevator.elevator_UI.imp_elevator_UI;

// Start of user code to add imports for ButtonCall

// End of user code

/**
 * Description of the class ButtonCall.
 *
 */

public class ButtonCall {
		
		// Start of user code to add fields for ButtonCall
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public ButtonCall() {
			// Start of user code for constructor ButtonCall
			super();
			// End of user code
		}
		
		
		/**
		 * Description of the method push.
		 *
		 * @param callingLevel
		 */
		public void push(Object callingLevel) {
			// Start of user code for method push

			// End of user code
		}
		
		// Start of user code to add methods for ButtonCall
		
		// End of user code
}