/**
 * LogicalView/simulation/elevator/elevator_UI/imp_elevator_UI/ButtonElevatorUI.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::imp_elevator_UI::ButtonElevatorUI uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:31 (24 novembre 2014) $
 */
package simulation.elevator.elevator_UI.imp_elevator_UI;

// Start of user code to add imports for ButtonElevatorUI
 

// End of user code

/**
 * Description of the class ButtonElevatorUI.
 *
 */

public class ButtonElevatorUI {
		
		// Start of user code to add fields for ButtonElevatorUI
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public ButtonElevatorUI() {
			// Start of user code for constructor ButtonElevatorUI
			super();
			// End of user code
		}
		
		
		/**
		 * Description of the method push.
		 *
		 * @param level
		 */
		public void push(Object level) {
			// Start of user code for method push

			// End of user code
		}
		
		// Start of user code to add methods for ButtonElevatorUI
		
		// End of user code
}