/**
 * LogicalView/simulation/elevator/elevator_UI/imp_elevator_UI/ElevatorUI.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::imp_elevator_UI::ElevatorUI uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:31 (24 novembre 2014) $
 */
package simulation.elevator.elevator_UI.imp_elevator_UI;

// Start of user code to add imports for ElevatorUI
 
import simulation.elevator.commonType.Direction;
import simulation.elevator.elevator_UI.int_elevator_UI.IElevatorUI;
import simulation.elevator.elevator_UI.int_elevator_UI.IPushableButton;
import simulation.elevator.elevator_UI.int_elevator_UI.IRequest;
import simulation.elevator.moveOptimizer.int_moveOptimizer.IMoveOptimizer;

// End of user code

/**
 * Description of the class ElevatorUI.
 * @uml.dependency   supplier="simulation.elevator.elevator_UI.int_elevator_UI.IConfigElevatorUI"
 */

public class ElevatorUI implements IElevatorUI{

	IPushableButton pushableButton;
	IRequest request;
	IMoveOptimizer moveOptimizer;
	
	@Override
	public int getLevelSelected() {
		
		return 0;
	}


	@Override
	public Direction getDirection() {
		
		return null;
	}


	@Override
	public void callElevator(int currentFloor, Direction direction) {
		//moveOptimizer.registerRequest(request);
		System.out.println("Appel de l'ascenseur de l'étage : " + currentFloor);
	}


	@Override
	public void levelPush(int level) {
		// TODO Auto-generated method stub
		
	}



	
	

		// Start of user code to add methods for ElevatorUI
		
		// End of user code
}