/**
 * LogicalView/simulation/elevator/resultAnalyser/imp_resultAnalyser/ResultAnalyser.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::resultAnalyser::imp_resultAnalyser::ResultAnalyser uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:32 (24 novembre 2014) $
 */
package simulation.elevator.resultAnalyser.imp_resultAnalyser;

// Start of user code to add imports for ResultAnalyser
 
import simulation.elevator.traffic.int_traffic.ITraffic;
import simulation.elevator.traffic.imp_traffic.DummyUser;
import simulation.elevator.ui.imp_ui.DummySimulation;
import simulation.elevator.resultAnalyser.int_resutlAnalyser.IResultAnalyser;

// End of user code

/**
 * Description of the class ResultAnalyser.
 */

public class DummyResultAnalyser implements IResultAnalyser {
		/**
		 * @uml.property  name="iTraffic"
		 * @uml.associationEnd  
		 */
		public ITraffic iTraffic;
		
		// Start of user code to add fields for ResultAnalyser
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public DummyResultAnalyser() {
			// Start of user code for constructor ResultAnalyser
			super();
			// End of user code
		}
		
		/**
		 * Return iTraffic.
		 * @return iTraffic
		 */
		public ITraffic getITraffic() {
		    return iTraffic;
		}
		
		/**
		 * Set a value to attribute iTraffic.
		 * @param iTraffic.
		 */
		public void setITraffic(ITraffic iTraffic) {
		    this.iTraffic = iTraffic;
		}
			
		/**
		 * Description of the method Load.
		 *
		 * @param file
		 */
		public void Load(String file) {
			// Start of user code for method Load

			// End of user code
		}

		/**
		 * Description of the method CreateFile.
		 *
		 * @param file
		 */
		public void CreateFile(String file) {
			// Start of user code for method CreateFile

			// End of user code
		}

		/**
		 * Description of the method Analyse.
		 *
		 * @param ListUser
		 */
		public void Analyse(DummyUser ListUser) {
			// Start of user code for method Analyse

			// End of user code
		}

		@Override
		public void Operation1() {
			// TODO Auto-generated method stub
			
		}

		@Override
		public DummySimulation getDummySimulation() {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public void setDummySimulation(DummySimulation dummySimulation) {
			// TODO Auto-generated method stub
			
		}
		
		// Start of user code to add methods for ResultAnalyser
		
		// End of user code
}