/**
 * LogicalView/simulation/elevator/elevator_UI/int_elevator_UI/Direction.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::int_elevator_UI::Direction uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:37 (24 novembre 2014) $
 */
package simulation.elevator.commonType;

/**
 * Description of the enumeration Direction.
 */

public enum Direction {
	/**
	 * @uml.property  name="uP"
	 * @uml.associationEnd  
	 */
	UP,
	/**
	 * @uml.property  name="dOWN"
	 * @uml.associationEnd  
	 */
	DOWN
}