/**
 * LogicalView/simulation/elevator/elevator/int_elevator/ElevatorState.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::int_elevator::ElevatorState uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:36 (24 novembre 2014) $
 */
package simulation.elevator.commonType;

/**
 * Description of the enumeration ElevatorState.
 */

public enum ElevatorState {
	/**
	 * @uml.property  name="sLEEPING"
	 * @uml.associationEnd  
	 */
	SLEEPING,
	/**
	 * @uml.property  name="mOVING"
	 * @uml.associationEnd  
	 */
	MOVING,
	/**
	 * @uml.property  name="tRANSITORY"
	 * @uml.associationEnd  
	 */
	TRANSITORY
}