/**
 * LogicalView/simulation/elevator/elevator/imp_elevator/ElevatorCageState.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::imp_elevator::ElevatorCageState uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:36 (24 novembre 2014) $
 */
package simulation.elevator.commonType;

/**
 * Description of the enumeration ElevatorCageState.
 */

public enum ElevatorCageState {
	/**
	 * @uml.property  name="oPENED"
	 * @uml.associationEnd  
	 */
	OPENED,
	/**
	 * @uml.property  name="cLOSED"
	 * @uml.associationEnd  
	 */
	CLOSED,
	/**
	 * @uml.property  name="mOVING"
	 * @uml.associationEnd  
	 */
	MOVING
}