/**
 * LogicalView/simulation/elevator/elevator/imp_elevator/MotorState.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::imp_elevator::MotorState uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:36 (24 novembre 2014) $
 */
package simulation.elevator.commonType;

/**
 * Description of the enumeration MotorState.
 */

public enum MotorState {
	/**
	 * @uml.property  name="rUNNING"
	 * @uml.associationEnd  
	 */
	RUNNING,
	/**
	 * @uml.property  name="wAITING"
	 * @uml.associationEnd  
	 */
	WAITING
}