/**
 * LogicalView/simulation/elevator/elevator/imp_elevator/SensorState.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::imp_elevator::SensorState uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:36 (24 novembre 2014) $
 */
package simulation.elevator.commonType;

/**
 * Description of the enumeration SensorState.
 */

public enum SensorState {
	/**
	 * @uml.property  name="dETECTING"
	 * @uml.associationEnd  
	 */
	DETECTING,
	/**
	 * @uml.property  name="nOT_DETECTING"
	 * @uml.associationEnd  
	 */
	NOT_DETECTING
}