/**
 * LogicalView/simulation/elevator/elevator/imp_elevator/SensorLocation.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::imp_elevator::SensorLocation uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:36 (24 novembre 2014) $
 */
package simulation.elevator.commonType;

/**
 * Description of the enumeration SensorLocation.
 * BLABLA+bla
 * ReBlabla
 */

public enum SensorLocation {
	/**
	 * @uml.property  name="tOP"
	 * @uml.associationEnd  
	 */
	TOP,
	/**
	 * @uml.property  name="bOTTOM"
	 * @uml.associationEnd  
	 */
	BOTTOM
}