/**
 * LogicalView/simulation/elevator/elevator_UI/int_elevator_UI/TypeRequest.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::int_elevator_UI::TypeRequest uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:37 (24 novembre 2014) $
 */
package simulation.elevator.commonType;

/**
 * Description of the enumeration TypeRequest.
 */

public enum TypeRequest {
	/**
	 * @uml.property  name="cALL"
	 * @uml.associationEnd  
	 */
	CALL,
	/**
	 * @uml.property  name="cOMMAND"
	 * @uml.associationEnd  
	 */
	COMMAND
}