/**
 * LogicalView/simulation/elevator/traffic/imp_traffic/Event.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::traffic::imp_traffic::Event uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:29 (24 novembre 2014) $
 */
package simulation.elevator.traffic.imp_traffic;

// Start of user code to add imports for Event
 


// End of user code

/**
 * Description of the class Event.
 *
 */

public class DummyEvent {
		
		// Start of user code to add fields for Event
		 
		// End of user code
		
		/**
		 * Constructor.
		 */
		public DummyEvent() {
			// Start of user code for constructor Event
			super();
			// End of user code
		}
		
		
		/**
		 * Description of the method trigger.
		 *
		 */
		public void trigger() {
			// Start of user code for method trigger

			// End of user code
		}
		
		// Start of user code to add methods for Event
		
		// End of user code
}