/**
 * LogicalView/simulation/elevator/traffic/imp_traffic/Traffic.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::traffic::imp_traffic::Traffic uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:29 (24 novembre 2014) $
 */
package simulation.elevator.traffic.imp_traffic;

// Start of user code to add imports for Traffic
import java.util.ArrayList;
import java.util.Random;

import simulation.elevator.elevator_UI.int_elevator_UI.IElevatorUI;
import simulation.elevator.traffic.int_traffic.ITraffic;
import simulation.elevator.traffic.int_traffic.IUser;


// End of user code

/**
 * Description of the class Traffic.
 */
public class DummyTraffic implements ITraffic {
		/**
		 * Constructor.
		 */
		private static int id;
		private ArrayList<IUser> listUser;
		/**
		 * Constructeur de la classe trafic.
		 * Itialisation de id à 0.
		 */
		public DummyTraffic(IElevatorUI elevatorUI)
		{
			super();
			id = 0;
			//Varaibles pour g�rer la creation des utilisateurs
			int etageDepart, etageArrive;
			int nbEtage = 10; //Le nombre d'�tages en dure pour les tests.
			int  nbUtilisateur = 10; //Nombre d'utilisateurs pour les tests.
			long dateDepart = System.currentTimeMillis();
			Random rd = new Random();
			etageDepart = rd.nextInt(nbEtage);
			
			//On cr�er des utilisateurs pour la version bidon du programme.
			//Instanciation de la liste d'utilisateur.
			listUser = new ArrayList<IUser>();
			//Boucle pour cr�er les utilisateurs
			for(int i = 0; i < nbUtilisateur;i++)
			{
				//On met à jour l'étage d'arrivé.
				if(etageDepart >= nbEtage/2)
					etageArrive = etageDepart - nbEtage/2;
				else
					etageArrive = etageDepart + nbEtage/2;
				//On met à jour la date de départ
				dateDepart += 1000;
				//On ajoute un utilisateur.
				//Creation d'un nouvel objet "Horloge".
				addUser(new DummyUser(elevatorUI,id,etageDepart,etageArrive ,dateDepart));
				//On met à jour l'étage de départ du prochain utilisateur.
				if(etageDepart != nbEtage-1)
					etageDepart++;
				else
					etageDepart = 0;
				id++;
			}
			
		}
		/**
		 * Pour la version bidon, permet de créer une liste d'utilisateur.
		 */
		public void addUser(IUser user)
		{	
			listUser.add(user);
		}
		/**
		 * Permet de renvoyer la liste d'utilisateur.
		 * @return listUser la liste des utilisateurs.
		 */
		public ArrayList<IUser> getListUser()
		{
			return listUser;
		}

		@Override
		public void trigger(long date)
		{
			for(IUser user : listUser)
			{
				if((user.getDateDepart() < date) && !user.getCalled())
					user.setCalled();
			}
			
		}
}
