/**
 * LogicalView/simulation/elevator/moveOptimizer/int_moveOptimizer/IMoveOptimizer.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::moveOptimizer::int_moveOptimizer::IMoveOptimizer uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:33 (24 novembre 2014) $
 */
package simulation.elevator.moveOptimizer.int_moveOptimizer;

// Start of user code to add imports for IMoveOptimizer
 
import simulation.elevator.elevator_UI.int_elevator_UI.IRequest;

// End of user code

/**
 * Description of the interface IMoveOptimizer.
 *
 */

public interface IMoveOptimizer {
    
	
	// Start of user code to add fields for IMoveOptimizer
 
	// End of user code

    /**
     *  Description of the method registerRequest.
     *
     *
     * @param request
     */
    public void registerRequest(IRequest request);

    /**
     *  Description of the method updatePosition.
     *
     *
     */
    public void updatePosition();

	// Start of user code to add methods for IMoveOptimizer
 
	// End of user code
}