/**
 * LogicalView/simulation/elevator/moveOptimizer/int_moveOptimizer/IMoveOptimizer.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::moveOptimizer::int_moveOptimizer::IMoveOptimizer uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:33 (24 novembre 2014) $
 */
package simulation.elevator.moveOptimizer.int_moveOptimizer;

// Start of user code to add imports for IMoveOptimizer
 
import simulation.elevator.Sequencer.int_sequencer.IEvent;
import simulation.elevator.commonType.Direction;
import simulation.elevator.elevator_UI.imp_elevator_UI.ElevatorUI;

// End of user code

/**
 * Description of the interface IMoveOptimizer.
 *
 */

public interface IMoveOptimizer extends IEvent {
    
	
	// Start of user code to add fields for IMoveOptimizer
 
	// End of user code

    /**
     *  Description of the method registerRequest.
     *
     *
     * @param request
     */
    public void registerCallLevel(int level, Direction direction, int destination);

    /**
     *  Description of the method updatePosition.
     *
     *
     */
    public void updatePosition();

	/**
	 * @return  Returns the elevatorUI.
	 * @uml.property  name="elevatorUI"
	 * @uml.associationEnd  inverse="iMoveOptimizer:simulation.elevator.elevator_UI.imp_elevator_UI.ElevatorUI"
	 */
	public ElevatorUI getElevatorUI();

	/**
	 * Setter of the property <tt>elevatorUI</tt>
	 * @param elevatorUI  The elevatorUI to set.
	 * @uml.property  name="elevatorUI"
	 */
	public void setElevatorUI(ElevatorUI elevatorUI);

	// Start of user code to add methods for IMoveOptimizer
 
	// End of user code
}