/**
 * LogicalView/simulation/elevator/moveOptimizer/int_moveOptimizer/IMoveOptimizerFactory.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::moveOptimizer::int_moveOptimizer::IMoveOptimizerFactory uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:34 (24 novembre 2014) $
 */
package simulation.elevator.moveOptimizer.int_moveOptimizer;

import simulation.elevator.elevator_UI.imp_elevator_UI.ElevatorUI;
import simulation.elevator.moveOptimizer.imp_moveOptimizer.MoveOptimizerFactoryImplementation;



public class MoveOptimizerFactory {
	
	public static IMoveOptimizer createMoveOptimizer(ElevatorUI dummyElevatorUI)
	{
		return MoveOptimizerFactoryImplementation.createMoveOptimizer();
	}
	
	
}