/**
 * LogicalView/simulation/elevator/elevator_UI/int_elevator_UI/IButton.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::int_elevator_UI::IButton uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:34 (24 novembre 2014) $
 */
package simulation.elevator.elevator_UI.int_elevator_UI;

// Start of user code to add imports for IButton
 

// End of user code

/**
 * Description of the interface IButton.
 */

public interface IButton {
    Object id = null;
	
	// Start of user code to add fields for IButton
 
	// End of user code

    /**
     *  Description of the method push.
     *
     *
     */
    public void push();

    /**
	 * Description of the method getId.
	 * @uml.property  name="id"
	 */
    public void getId();

	// Start of user code to add methods for IButton
 
	// End of user code
}