/**
 * LogicalView/simulation/elevator/elevator_UI/int_elevator_UI/IconfigElevatorUI.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::int_elevator_UI::IconfigElevatorUI uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:34 (24 novembre 2014) $
 */
package simulation.elevator.elevator_UI.int_elevator_UI;

// Start of user code to add imports for IconfigElevatorUI
 

// End of user code

/**
 * Description of the interface IconfigElevatorUI.
 */

public interface IConfigElevatorUI {
    /**
	 * @uml.property  name="iconfigElevatorUI" default="null"
	 * @uml.associationEnd  
	 */
    public IConfigElevatorUI iconfigElevatorUI= null;
	
	// Start of user code to add fields for IconfigElevatorUI
 
	// End of user code

	// Start of user code to add methods for IconfigElevatorUI
 
	// End of user code
}