/**
 * LogicalView/simulation/elevator/elevator_UI/int_elevator_UI/IRequest.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator_UI::int_elevator_UI::IRequest uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:34 (24 novembre 2014) $
 */
package simulation.elevator.elevator_UI.int_elevator_UI;

// Start of user code to add imports for IRequest
 
import simulation.elevator.commonType.Direction;
import simulation.elevator.commonType.TypeRequest;
import simulation.elevator.traffic.imp_traffic.DummyUser;
import simulation.elevator.moveOptimizer.imp_moveOptimizer.DummyMoveOptimizer;

// End of user code

/**
 * Description of the interface IRequest.
 *
 */

public interface IRequest {
    public Object Floor=null;
	
	// Start of user code to add fields for IRequest
 
	// End of user code

    /**
     *  Description of the method getType.
     *
     *
     * @return ret
     */
    public TypeRequest getType();

    /**
     *  Description of the method getCallType.
     *
     *
     * @return ret
     */
    public Direction getCallType();

    /**
     *  Description of the method getLevelSelected.
     *
     *
     * @return ret
     */
    public int getLevelSelected();

	/**
	 * @return  Returns the dummyUser.
	 * @uml.property  name="dummyUser"
	 * @uml.associationEnd  inverse="iRequest:simulation.elevator.traffic.imp_traffic.DummyUser"
	 */
	public DummyUser getDummyUser();

	/**
	 * Setter of the property <tt>dummyUser</tt>
	 * @param dummyUser  The dummyUser to set.
	 * @uml.property  name="dummyUser"
	 */
	public void setDummyUser(DummyUser dummyUser);

	/**
	 * @return  Returns the dummyMoveOptimizer.
	 * @uml.property  name="dummyMoveOptimizer"
	 * @uml.associationEnd  inverse="iRequest:simulation.elevator.moveOptimizer.imp_moveOptimizer.DummyMoveOptimizer"
	 */
	public DummyMoveOptimizer getDummyMoveOptimizer();

	/**
	 * Setter of the property <tt>dummyMoveOptimizer</tt>
	 * @param dummyMoveOptimizer  The dummyMoveOptimizer to set.
	 * @uml.property  name="dummyMoveOptimizer"
	 */
	public void setDummyMoveOptimizer(DummyMoveOptimizer dummyMoveOptimizer);

	// Start of user code to add methods for IRequest
 
	// End of user code
}