/**
 * LogicalView/fr/univavignon/m1ilsen/aa/simula/Sequencer/int_sequencer/ISequencer.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::Sequencer::int_sequencer::ISequencer uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 16:04:27 (24 novembre 2014) $
 */
package simulation.elevator.Sequencer.int_sequencer;

import simulation.elevator.Sequencer.imp_sequencer.SequencerException;


// Start of user code to add imports for ISequencer
 

// End of user code

/**
 * Description of the interface ISequencer.
 *
 */

public interface ISequencer {
	
	// Start of user code to add fields for ISequencer
 
	// End of user code

    /**
     *  Description of the method Sequencer.
     *
     *
     * @param Elevator*
     * @param start
     * @param duration
     * @param contraction
     * @param expansion
     */
    //spublic void Sequencer(ISequencable elevator, ISequencable traffic , long start, long duration, long contraction, long expansion);
	void addProcess(IEvent event) throws SequencerException;
    /**
     *  Description of the method start.
     *
     *
     */
    public void start();

	// Start of user code to add methods for ISequencer
 
	// End of user code
}