/**
 * LogicalView/simulation/elevator/elevator/int_elevator/IElevatorConfigurator.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::int_elevator::IElevatorConfigurator uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:33 (24 novembre 2014) $
 */
package simulation.elevator.elevator.int_elevator;

import simulation.elevator.Sequencer.int_sequencer.IEvent;


// Start of user code to add imports for IElevatorConfigurator
 

// End of user code

/**
 * Description of the interface IElevatorConfigurator.
 */

public interface IElevatorConfigurator extends IEvent {
   

	public void setParam();/*Direction direction, ElevatorCageState cageState,
			ElevatorState elevState, long speed, int currentLevel, int levelNb, long distanceBtw);*/


	// Start of user code to add methods for IElevatorConfigurator
 
	// End of user code
}