/**
 * LogicalView/simulation/elevator/elevator/int_elevator/IElevatorControl.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::int_elevator::IElevatorControl uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:33 (24 novembre 2014) $
 */
package simulation.elevator.elevator.int_elevator;


// Start of user code to add imports for IElevatorControl
 

// End of user code

/**
 * Description of the interface IElevatorControl.
 *
 */

public interface IElevatorCommand {
	
	// Start of user code to add fields for IElevatorControl
 
	// End of user code

    /**
     *  Description of the method move.
     *
     *
     * @param direction
     */
    public void move(Object direction);

    /**
     *  Description of the method stopNextLevel.
     *
     *
     */
    public void stopNextLevel();

	// Start of user code to add methods for IElevatorControl
 
	// End of user code
}