/**
 * LogicalView/simulation/elevator/elevator/int_elevator/IElevatorInfo.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::elevator::int_elevator::IElevatorInfo uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:33 (24 novembre 2014) $
 */
package simulation.elevator.elevator.int_elevator;

import simulation.elevator.commonType.Direction;
import simulation.elevator.commonType.ElevatorState;

// Start of user code to add imports for IElevatorInfo
 

// End of user code

/**
 * Description of the interface IElevatorInfo.
 *
 */

public interface IElevatorInfo {
	
	// Start of user code to add fields for IElevatorInfo
 
	// End of user code

    /**
     *  Description of the method getCurrentFloor.
     *
     *
     * @return ret
     */
    public int getCurrentFloor();

    /**
     *  Description of the method getState.
     *
     *
     * @return ret
     */
    public ElevatorState getState();
    public void setDirection(Direction direction);
	public void setElevatorState(ElevatorState elevatorState);
    // Start of user code to add methods for IElevatorInfo
 
	// End of user code
}