/**
 * LogicalView/simulation/elevator/resultAnalyser/int_resutlAnalyser/IResult.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::resultAnalyser::int_resutlAnalyser::IResult uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:36 (24 novembre 2014) $
 */
package simulation.elevator.resultAnalyser.int_resutlAnalyser;

import simulation.elevator.ui.imp_ui.DummySimulation;

// Start of user code to add imports for IResult
 

// End of user code

/**
 * Description of the interface IResult.
 */

public interface IResultAnalyser {
    /**
	 * @uml.property  name="iResult" default="null"
	 * @uml.associationEnd  
	 */
    public IResultAnalyser iResult = null;
	
	// Start of user code to add fields for IResult
 
	// End of user code

    /**
     *  Description of the method Operation1.
     *
     *
     */
    public void Operation1();

	/**
	 * @return  Returns the dummySimulation.
	 * @uml.property  name="dummySimulation"
	 * @uml.associationEnd  inverse="iResultAnalyser1:simulation.elevator.ui.imp_ui.DummySimulation"
	 */
	public DummySimulation getDummySimulation();

	/**
	 * Setter of the property <tt>dummySimulation</tt>
	 * @param dummySimulation  The dummySimulation to set.
	 * @uml.property  name="dummySimulation"
	 */
	public void setDummySimulation(DummySimulation dummySimulation);

	// Start of user code to add methods for IResult
 
	// End of user code
}