/**
 * LogicalView/simulation/elevator/traffic/int_traffic/ITraffic.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::traffic::int_traffic::ITraffic uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:33 (24 novembre 2014) $
 */
package simulation.elevator.traffic.int_traffic;

import simulation.elevator.Sequencer.int_sequencer.IEvent;

// Start of user code to add imports for ITraffic
 

// End of user code

/**
 * Description of the interface ITraffic.
 */

public interface ITraffic extends IEvent {
  		/**
		 */
		void addUser(IUser user);
}