/**
 * LogicalView/simulation/elevator/traffic/int_traffic/IUser.java
 *
 * File generated from the Ascenseur::LogicalView::simulation.elevator::traffic::int_traffic::IUser uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 24/11/14 15:55:33 (24 novembre 2014) $
 */
package simulation.elevator.traffic.int_traffic;

/**
 * Description of the interface IUser.
 *
 */

public interface IUser {

	void display(long T);
	int getId();
	int getEtageDepart();
	int getEtageFin();
	long getDateDepart();
	void setDateArrive(long dateArrive);
	void setCalled();
	boolean getCalled();
	long getDateArrive();
	 
}